services:
  caddy:
    # https://hub.docker.com/_/caddy/
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "3900:3900"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
  garage-s3:
    # https://hub.docker.com/r/dxflrs/garage/tags
    image: dxflrs/garage:v2.3.0
    restart: unless-stopped
    # listening on port 3900
    volumes:
      - ./garage.toml:/etc/garage.toml
      # volume needs speed
      - ./garage_s3/meta:/var/lib/garage/meta
      # volume needs space
      - ./garage_s3/data:/var/lib/garage/data
volumes:
  caddy_data:
  caddy_config:
