services:
  s3_object_storage:
    # https://hub.docker.com/r/dxflrs/garage/tags
    image: dxflrs/garage:v2.3.0
    restart: unless-stopped
    # required for internal RPC and maximum network performance
    network_mode: host
    volumes:
      - ./garage.toml:/etc/garage.toml
      # needs speed
      - /var/lib/garage/meta:/var/lib/garage/meta
      # needs storage
      - /var/lib/garage/data:/var/lib/garage/data
    environment:
      # openssl rand -hex 12
      - GARAGE_DEFAULT_ACCESS_KEY=GK0d12a14e9397dd5e222b7b4d
      # pwgen -sBcn 25 1
      - GARAGE_DEFAULT_SECRET_KEY=pcyhu9yhzJUCsa4yX37twEC3c
