apiVersion: v1
data:
    password: ENC[AES256_GCM,data:LR77Is4XhqAHZfUz01ju/Id0vBLSjcqS,iv:jPECO6NrnBjdmYqjnQGBX/G/KtbxiKtVtkxlhYT7KRY=,tag:ZEeLBal0UoZiw4LNmqBQSg==,type:str]
kind: Secret
metadata:
    name: redis
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybWozTmJzSjJyYkw1dEE5
            ZW02RTk0NWpRN3ZidnFwbm5FbWh0ZWROZGtrCkViWHpFd1luSFFyRlU2WUtxRE5P
            bVdldGxYU0xmRkpxSDUrZVRHUnQzblEKLS0tIGQ3b04xS09iemVGMGJiVjJKMndy
            TzdiOHNTTEFCeEczMXlqYTloZ1YvMEUKcub0JPhDI6XbNmWstZjSi87wZVBuhKRU
            t54LCdYab39rM7m4hTpxCb0SJJQ5NWaoU3wteVt5SvWg95WFJ3z/hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jln6w6rr3gphvgzxuuwulyhp2ssu2df8np0vc5ppvq9vrx4va4fqsunfxn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T15:48:50Z"
    mac: ENC[AES256_GCM,data:COh/htnTznloT3xbvJiJ9dp3P5liZ1o44Xq5VrI/k0u5WDtwnYCYSo61Zpp2tj7ZOKncVL1GaXLRYWu9Lec+a60lRUSwUZNkV3R47vDeAVO5/5kGTE1Ig0AMVhIM1svKfA7iPsTJJG7MJ8skeXzcKRSxm/E1ywlRN/eHwIeRb+g=,iv:MHnSOP9J3Herr+IX/M8eAuAj/sl3twQuP7uaqNYf8Ag=,tag:GutScA2w6DxG2gPh2PxHww==,type:str]
    version: 3.13.0
