apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Dgiue/37Zu8MN8exRxV4NXuumwLrzvEZ,iv:qh3sF1pa2pNqyjI7sSAB0AHQxboNJoyNCQQp4zcsgfg=,tag:S+KWGiTMlRmDwZNQ/x4Ljw==,type:str]
kind: Secret
metadata:
    name: postgresql
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwekhOVWVvM1B1UlhpUlpo
            NmgrMERTY3hBRFB6MlgvdjN4RHVFL3lwT1RnCnJuQnZsTENNejlXbnQ0K3l0NTU2
            RHRVTzhBa2dkYjl3L21sSTNZL3RuS0EKLS0tIHpZdkhVcGhSMk9LV1JIR2s5ZTla
            bUt2dlNESThwQldIVmdRZzZIL3YyVm8KZu7eGgKjrZnySYypBU2UrgbdTlJkrvOI
            IfDhUHz7jZb7PzNshUejPLTi30B0awB9rzX9DV6tYntrQ8W0GG2aaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jln6w6rr3gphvgzxuuwulyhp2ssu2df8np0vc5ppvq9vrx4va4fqsunfxn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T15:40:10Z"
    mac: ENC[AES256_GCM,data:kfiDeJx2bSvA26jr8j2DhWPiVT6eu4aRf1lxTWeiqRDvUV2N50OI6qRiSmSktSz994h9Niq0s9LIeOz5uhllnAaIH8ycEFkLyVCYWkVQXeMZpy53K42TQyd45MCVh6svHDV2P6edMAimRQ/Vf4lRUcHC5NWI65kEpusFCo1H7Hg=,iv:13Pv2eI1Ywy6+roNdayHCZTyupsjN0BgYAeVW2BF49M=,tag:puBhVhg3PKR27qHzTvhVuw==,type:str]
    version: 3.13.0
