apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:tsZ/aXTgjKakPB2xmMPDWJKLuQd5IwxC/5SCiw==,iv:0su57FHWeiA1pG/sDZMApBfnPd3pjLXJfXrwsELH+bA=,tag:Hq/2myUQWinR5jn6+71TVw==,type:str]
    metrics-password: ENC[AES256_GCM,data:YX5QM1zMbOrO1s+/jsrSqiWE3ozGViktDmA2ng==,iv:+Ym7yNNJg9tizA+bomoI7Oh3IkWUFyQfNIWlFdR3n38=,tag:+S6kTsEfbzJfsoUk5qUSDg==,type:str]
    replication-password: ENC[AES256_GCM,data:2pR4H1aU133+6L9OtH3wsldIPHvm1CP5R7MlLg==,iv:wzPsyzSOUi06XwzLldcO1WRUsG9W3QpI1ILLZFuDGHE=,tag:Of+kJSkiUSmHgrwh6ucq7A==,type:str]
    user-password: ENC[AES256_GCM,data:zUuPN+sooZhCY/B2zM4T9H6Muepvf3xxrDEY5w==,iv:d9/G5SsHSsu9Pm2nCMOWCHw1UjnsqyI+5p4LrMTAH0k=,tag:7eaY+P4C0optq+stduDC4Q==,type:str]
kind: Secret
metadata:
    name: postgresql
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbGltK2NaU0xRMTNsclZM
            QnVyWFJ6Wlc3TmJsS2ZSK1VzYTk5T2tpQ2pBCktqaWtrNHkySnAwODIxWmVVYzlK
            anoxL29FaExDaklDaWU3OFk2alp6TEkKLS0tIFhuMkNEWlRjeEdQU3FKQUJrZVZE
            djdRUTFZZWZJVGRZTUIvOXRhSFZQeTAKF4t07UlJFCuFjvkUkbBkRDhFx+WWvKNW
            n3TLjALxEQ/OKN9yhK9z2IKz6uLimWdcCrpSqwsIFPZz5QBXou9+8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lk65zv3r97ktvctw7ukm5dccph56u5y59gm5unde226je037r36q6n04dv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T09:05:36Z"
    mac: ENC[AES256_GCM,data:YTR6fTmYYGm1MN/7kTyjozfNTtyoNIvVX2lUedgrITzorFxQvtBiGO7j2k0TKjvI6KQWDzkIAG1o403Q3nTp4gQo06q1y13Y7cTBlHHRFFEGM1dfxM3P4qHa7yEUIlqwiPvEMqQ8NsON1KNRLEjMxrfiMBuz7zQAnUEwDxm0aII=,iv:i3wPN75Ix+9NDPXqipf1P9papj7KTza7L67aCSl3dFM=,tag:36vPUf6ZEgQvHTi8HScjjA==,type:str]
    version: 3.13.1
