apiVersion: v1
data:
    password: ENC[AES256_GCM,data:bGb6iDG+Macwqia22ypxgdq96RX3lJ/j,iv:z7kSQcuctP8tO+K2pgRTh0akaxv2X6qzznePEgYa3NE=,tag:WhUTV4eHsqh2LEHBFbAWjw==,type:str]
kind: Secret
metadata:
    name: postgresql
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cDc5bEJLSDl0R2RPOXpm
            OVAybktERXhneFNqTy8wcjg3YnY5WmdRQkhzClNZYVZKblllb0h5Zmh6TWxlM2lh
            Q1N3eEs5aWhwWkFUQ0F4ZXFJY0lmWXMKLS0tIDVLT25KQXZ6TmpQQ0pMc0VyYzY2
            UFVpb0xTTkNlaGdicTA3elhheDlxajgKajCsKI/3uTcoYM2IeIEKflYdZkCwNmFl
            vJaD/cCUUDTwCgCQO4oueookh65HA9RTKMh5CXgL/jNsD3bwIJpKpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vax2enxd63gseencrgw6me5duk947dfxl0nfyh5sqmarq996dqjsexljll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T14:21:45Z"
    mac: ENC[AES256_GCM,data:EPxc/mIZBiWZNAkfH3wU8s5papjUjjTcR0UDBzS/mlcfHGAzrve2WV0Exg58PwdaAVwADr3FOh9cL0D8mVT8mwRW7RWqMhA2z5N7Zk+5oS3J4LVTeJzL2HY7XxZfm475Wo/PQckVcq1lJYEUCkIcfY4Q9ebiVReFLGKDL8RGMno=,iv:vc1a0nmnOfaxhGI1ApJf+1Bt5y2OKyaeuMTiuN/IRAA=,tag:7/4dVFh+l5L+cbXYOdV88w==,type:str]
    version: 3.13.0
