apiVersion: v1
data:
    password: ENC[AES256_GCM,data:7cFfeGfO0enpGwTWH0u3XllJf/orGam/,iv:z4WN9h0pEWwj2VRL5n346zLposQcSQltR2//dxYR/mQ=,tag:hzW4zcbXtfWZszRv4ZTVaw==,type:str]
kind: Secret
metadata:
    name: redis
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS3pXSG9wcCsvN2FNbG9h
            NSthR0ZrSVNnUVJaU0JLNUxDUkRESXVmVXpJClZocmF5QUpuTExDQnp1bE5KTFk3
            aTROMFVua0Q2Z3EvMHNpUzh1Tm9qTlkKLS0tIHVxM3p0RStVWS9LZ3gxODM3ck5p
            RVdBUUVacHI3cTRBRTZCV25BWmJtRncKluIGcJSEYatwBLkLzS9kH8aWrp2QMEOH
            eVoOdvUWrCCQopVwbS7DGJz/EwOYYbbutD4r4nfsRwo2/DnxFga+9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vax2enxd63gseencrgw6me5duk947dfxl0nfyh5sqmarq996dqjsexljll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T14:22:12Z"
    mac: ENC[AES256_GCM,data:tHu6ONdCwoHd5EP/NK9V1LWwcGXSZrp4VII8I1IEZDqZa9NphWZdrEOQ+D+drlbTEr/GduA97CWQRL1RvqJEzi7j2ev7bby3kcp5OMqrLq8DRSAYmYEjEpHDYV2WAaE48AUAXWfpS31VqjMYFP0jRrFOdUupUZkln9+rkIQKvn4=,iv:f92wDlZ2fenanUyOEits2c8lKlT+IK76evyJ5u2RsuM=,tag:F1LNuLe1RSzmsRasx+J2kw==,type:str]
    version: 3.13.0
