apiVersion: v1
data:
    password: ENC[AES256_GCM,data:wcqB7CrTQ5VT6/ZiWh2WGe+xqrh8yBKr,iv:Eatm9QesldsdCkBQqUrn7fGdA/5/rPLLQS/s7GUPjT4=,tag:zOR6nuhJLPKdupSOzL+AwA==,type:str]
kind: Secret
metadata:
    name: postgresql
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM1Rra0hNcU5TWE9rOUk5
            UndxUEtIZDhyaWkyRmJMQTZkc3hQY093bERBCkgzQ3dQWnJlekFFdUd4aUlsR1pv
            VXBJVUpvUFRZTEdRRXFzaFpCc04xaDQKLS0tIE5sSENHbG1BdEt2eG5FWlp1bmZZ
            ajVCQ3VBY2hmM215U2ZLVDdteWszMTQKXs1IXLgnxEuH9Jd2EQunDXXxRDojCjyC
            YYU89+PrRer3gxzagkT9CxjAQPo2Xy6ONBfJ96lfxQ0vmBpDDpNP1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jln6w6rr3gphvgzxuuwulyhp2ssu2df8np0vc5ppvq9vrx4va4fqsunfxn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T15:40:29Z"
    mac: ENC[AES256_GCM,data:7U+OGqn8s6Vd+/K3aEWt6nKeRoUw6+O2KadF9L+82gGfLacwVI7OLfLLDoY+5RHB0yX7eYS3bknanZMR5teTkzvrLf+00ImYGZ/LHUCtyOkXG89kmc7DjLsRPLiQUgKYKj5blIgSCOEWB1tTa5ouxi99nmiH2XrXW6G7/k+BoBI=,iv:ypF+KVIeJqncmNwZ0QoiOt/RT6Nt5QPjhfLInqGIgl8=,tag:sWZe/7NiQv9htnaOwvUW2g==,type:str]
    version: 3.13.0
