apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
  namespace: nextcloud
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: nextcloud
spec:
  interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      # Automatically rollback on failure
      remediateLastFailure: true
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: nextcloud
  values:
    # Reference: https://github.com/bitnami/charts/blob/main/bitnami/postgresql/README.md
    global:
      defaultStorageClass: "longhorn-2node"
    auth:
      username: "nextcloud"
      database: "nextcloud"
      existingSecret: "postgresql"
      secretKeys:
        adminPasswordKey: "admin-password"
        userPasswordKey: "user-password"
        replicationPasswordKey: "replication-password"
        metricsPasswordKey: "metrics-password"
    volumePermissions:
      enabled: true
    primary:
      persistence:
        enabled: true
        size: "10Gi"
      nodeSelector:
        # In case of an outtage of this node, change it to the secondary node name
        kubernetes.io/hostname: "dean-homelab"
