apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
  namespace: nextcloud
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/redis
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: nextcloud
spec:
  interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      # Automatically rollback on failure
      remediateLastFailure: true
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: nextcloud
  # ref: https://github.com/bitnami/charts/blob/main/bitnami/redis/README.md
  values:
    architecture: standalone
    auth:
      existingSecret: "redis"
      existingSecretPasswordKey: "redis-password"
    master:
      persistence:
        enabled: false
      nodeSelector:
        # In case of an outtage of this node, change it to the secondary node name
        kubernetes.io/hostname: "dean-homelab"
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          memory: 512Mi
