apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:Ec9l0aUttXohvlPmVBsKMFKuvGMq7d9O2qdZoA==,iv:9oE5l0VHDgDSdK9FJ9PEEGsXGEkIkTna62lOrJgDnSg=,tag:ozOXuHiADu8mOSisYua+jA==,type:str]
    metrics-password: ENC[AES256_GCM,data:HWwrMcgO91O+ZobpwDfnsa+8ukSxy6oO3IwgTg==,iv:U/odZOlPaEhoVXbwK+s6ql02Vjd1FS9C5/JC/jYCtqQ=,tag:hmoIfVUYjt6aY9IxbpbQjA==,type:str]
    replication-password: ENC[AES256_GCM,data:/RR6+/UM2QQrwhs/+tTx4Hudnyg4gzUilKV90Q==,iv:oVWFJpZI2JqOC9E2O9uV4YKZWwGX/nF5aDXYBdSTUvI=,tag:x6Wq2Jc1az+mFKTlZtJmQQ==,type:str]
    user-password: ENC[AES256_GCM,data:GSg6DY1yQBbHYe5XmeNm8SkMpBpyt1uySvUjXQ==,iv:4+lROPzSyarNdVphEZCkR1k9wg6RYWANgbQ1u+2P54Y=,tag:ARPwFpbTLe4plVWietwRnQ==,type:str]
    username: ENC[AES256_GCM,data:tBeMeReFfUZbr9Hf,iv:/xAp+WnIlQVk3xJaILFaHoGLFsyZMyYXosAWdXdDu/E=,tag:/pwgbIiNrJFaMWzYV7yM0g==,type:str]
kind: Secret
metadata:
    name: postgresql
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBR0NZcW9uQ1RBV2MxdlBK
            L25QQVRqd1B5ZXdBVjNVNGlESWlLSVFmWEd3Ck8rTGR3a2UyTGpTaXo3UUd0Q2t0
            L3VmWWIvalhMS0ZySkhYZ2NybEJ5YkkKLS0tIFRteGs5ZEVRMk91Z09CMS9tRnow
            dFRtOE1yNmJjYzhMeTYySW8zWVUwMGcKZiyxtdyxGHdoNp5DXRBpnFkAPjMaRsYA
            6RMO2Y6AjOPT116wF/L/SLxmhS6Lv/1ODHAX78Q+xrQuyF8YOTJ7qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7rq0snpc5k39qw68mw0z48ndjgr0a4pdu6ehmcfn4zk8utc7dxqxaxn6g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T16:20:51Z"
    mac: ENC[AES256_GCM,data:m/qxGspBOHisTZXRe9UWBfCJATouqRDypUqLGkakpT9Lq3tixkEZYj5pzVHvERLqf6anXaDoEvC8M7CvWW0/0AVxpildsfFYtc/QrmaDXzb/slmCQ51vav+pbCfr1FLex5CBGJI0lifg5qEcK7JVqyTkVwH/uZ5TGjUo3gswh/M=,iv:wSP2E6QVM+ykO/xWRvXwDYmMOECpdKYofjEhvikIyCs=,tag:B9W9m7qv/K/An1Ta0VcaMA==,type:str]
    version: 3.13.1
