apiVersion: v1
data:
    redis-password: ENC[AES256_GCM,data:dVxVc9QQyDTlIldxSq875AHs5xqIEl86cIdWJA==,iv:8kOnR48Hwg0B7f91Wtumssj3Ngiv1/iIYpEiZ7jq7MI=,tag:SriaXfv5oUoza1mZ+b6dQw==,type:str]
kind: Secret
metadata:
    name: redis
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQitPSTVGS3Evd2Fjd1ds
            QkdoWTVDV1ppRlNXNjdLbXlDVFJoQ2Fqb3dvCk4ybW9ITWVrNk53NHlKTm5NUy9D
            WHMyYzdBeGJIVlE0cFFFVHU2SFRUS0UKLS0tIGl0RWNSZmU4dkZrUnlHZjJKM0Zx
            VHd3VzkyaUJnQ1VDMFgyTjVURmo3WVUKgESdnhab6xx1y6muXBPnerjY/LxRoCUx
            qzCacili/hzb8mLbUg3G3OifYHqey+OSIpbvpP9B4P/yYhWg4vx2xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7rq0snpc5k39qw68mw0z48ndjgr0a4pdu6ehmcfn4zk8utc7dxqxaxn6g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T12:59:54Z"
    mac: ENC[AES256_GCM,data:tKYMHKZTWYzmNxZeKAmXvWxi7aDzT3XInI8Xms5FnIi7zozeQrtrnf/fxt5BhqCQ64wwqMykGWEtqInT1VHh3V4C7fFTdtKxoDU9jBAIQrJQveNkf38buR3kW/0uyhevPzckqKWyJ80V419iJVUKloaSh5tWYSIbjqhq2OwjRuA=,iv:0skdVQ9L4T88jO2Up5BFU6Q7Q+4lI3fjeIb3rrAi1gI=,tag:Di4t9jwmttYtDecLyTccGw==,type:str]
    version: 3.13.1
