apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:Ynt8paBYi3t3Wh9sCI/yV51Ypb4vIuHaOpXyKg==,iv:yDs25L0Vsnx5JOJfYOYFBio4DYIcXcZ3olcxGF0bvp4=,tag:BFDbouBGtCgxheZe67kb8Q==,type:str]
    metrics-password: ENC[AES256_GCM,data:021xKfK3xLzc1jFplfKx5aCUWMfOO32oDR53dA==,iv:Pb1Dda/DQYKie0GTiU+GUtQQc6X+ITHC7oUzUZy/MSY=,tag:4RoIh3B46UzQgVy4FkpN8g==,type:str]
    replication-password: ENC[AES256_GCM,data:v9lCEfYGgfOVIqjzLe7Bi6g1QwlamMG8Rdsu0A==,iv:NsMobfrfpUYfurvybd1eQIiXvyoUKpnuTFjo03Bfzw0=,tag:IMB6k0IFyGpGbW0RVa8Kog==,type:str]
    user-password: ENC[AES256_GCM,data:1dLmnbMJKNbDWvKPUkLKh+0Dk5ylxX8SHU+6sA==,iv:BLDffCCD0hH2bSIS30Xup1XYgpTmLaj7d5OrlSqWyOQ=,tag:c/rQk7vJV/lWnGOQBEilxA==,type:str]
kind: Secret
metadata:
    name: postgresql
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a0FBR0toUWcyQjl1V2pN
            QWw1Wi8wcE9HM3FvNjVMOWtrYk5STUk2a0Q4CkFRc2FDbm5wN2hhWjkxcVFON3Y2
            VnY2UHNUU3RaQTlselFOVzZ3ZXZ3TXMKLS0tIFM5SmY5UVhsNHVFK3NORDNTem5i
            d2J4UXhyaXZleFV3d2xsNGNzSVRqcVkKaLKXWsnk7786ylEwJdWiaoE7C4ZI5vMP
            fHd1wUlMJo1rGe0KgHT6t33ou/4DoFiXC3GVpLfCJOB3tfrIh8a6hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7rq0snpc5k39qw68mw0z48ndjgr0a4pdu6ehmcfn4zk8utc7dxqxaxn6g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T12:58:56Z"
    mac: ENC[AES256_GCM,data:IdhjKEpaM/G20Y2HGUD/V3eQs3pqdqjfy0wH+G7eYbcU89pY9gtEQ8sMnN2FB6D2/wmmPznayzLXMmjjxdt/rIc4dJRloeQt47vKtNy484DNsMlFyfj2MiUJ1lKr0Repk/tT9Jf1EWGC710rFuJx1yNJVD8G8j1U74lfIzgAXOc=,iv:Mu1GRi7LEwadBCUyNOiM8ihSEMwLF1kEr/sBixOkO3c=,tag:z/CQrKxcdHYETrhUnddJZg==,type:str]
    version: 3.13.1
