apiVersion: v1
data:
    password: ENC[AES256_GCM,data:sCLaY2A3vpOauOgzWA0CKfeXnZic2TEjGkP6yO7HVd+JjB+v,iv:G/wB2JnJFhWTdDfI7pWzEcruXg9Obd0kIkvMsMUzVLA=,tag:GmaaElqmdrPJnxs0B3Ug/w==,type:str]
    username: ENC[AES256_GCM,data:EDPl9GlluuE=,iv:TF98M500rwLYX297OXE19Jx7WQxdeLtGIuZ5yn0W5gw=,tag:uc/sdNpHKxPg9tLEE2T93g==,type:str]
kind: Secret
metadata:
    name: nextcloud
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa0pVOXhWOGsyd3AydmdE
            WjNxd0lLZllxN1piZlFKRFBrUGJ5VUlyMm1ZCm8wUjllTU0wcjJ3V3NXTXJldWFC
            TFhiQ1FkeFFJUEsvT2ZZNlYxTjBmb00KLS0tIE5ndTJPUWtyRUFEcGRNYk92WmIr
            cVRPSENBNzZJL0l2d2JqUGM1Qk8welEKi1LFSqNVowzHM1iV/y1Ai6t3t+e5ZWV0
            qj8Qs3zN2qnGA1WJ8xsJl+M/VcMkGDSlxAWgId9/TO94Ub+4mznddA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7rq0snpc5k39qw68mw0z48ndjgr0a4pdu6ehmcfn4zk8utc7dxqxaxn6g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:12:11Z"
    mac: ENC[AES256_GCM,data:zylwLKbkqeoNafv8wcRQmPr7IRTQ2Buhh9rQWSwV379TOEsGK59RioXXXv4kSan51hPN3xQ879p10rppv7J5dQj6zCAc/cZUm1wtUmLzg9hPUn81I+BjXQD12SNp+35DbsP6EEfVTuO5JwHJhNT9uWNIQR41qANhFk9JWzH2o9M=,iv:DS4+MFaPUiSwMv+AuuCARE8zVWeA/FT/VxV0iv5U6b0=,tag:z6j6MQU1bbA1MUjo1iH4SQ==,type:str]
    version: 3.13.1
