apiVersion: apps/v1
kind: Deployment
metadata:
  name: deanqx-com
  namespace: deanqx-com
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: deanqx-com
          image: ghcr.io/deanqx/deanqx.com:20260903-170927-118156b # {"$imagepolicy": "deanqx-com-staging:deanqx-com-staging"}
