apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-issuer-production
spec:
  # Reference: https://cert-manager.io/docs/configuration/acme/http01/
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dean@kowatsch.de
    privateKeySecretRef:
      name: tls-account-key-production
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: cilium
              namespace: cilium-gateway-system
              kind: Gateway
