# ref: https://fluxcd.io/flux/guides/image-update/
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: deanqx-com
  namespace: flux-system
spec:
  image: ghcr.io/deanqx/deanqx.com
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: deanqx-com
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: deanqx-com
  filterTags: # example: 20260818-185547-16c4f14
    pattern: "^[0-9]{8}-[0-9]{6}-[0-9a-f]+$"
  policy:
    alphabetical:
      order: asc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deanqx-com
  namespace: deanqx-com
  labels:
    app: deanqx-com
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Spin up 1 new pod before killing an old one
      maxSurge: 1
      # Always keep 100% (2 pods) ready to answer requests
      maxUnavailable: 0
  selector:
    matchLabels:
      app: deanqx-com
  template:
    metadata:
      labels:
        app: deanqx-com
    spec:
      containers:
        - name: deanqx-com
          image: ghcr.io/deanqx/deanqx.com:20260818-192132-bb91191 # {"$imagepolicy": "flux-system:deanqx-com"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
