apiVersion: v1
data:
    password: ENC[AES256_GCM,data:JYb5a5At2Uyg4hpK+0liIua6Ulwp12e1tisXecMWrLHk0vJD,iv:DQIgII2rQPBS7bO1ibmachAzevBEF9qgXCq1xTGviIg=,tag:DTorINl5Ub1ftzFGVd7R6w==,type:str]
    username: ENC[AES256_GCM,data:VvRBP78pQZs=,iv:tGN8nvVLJ57bHPqmMiNZb2e6ZOn9fqziPubSm4zV0a8=,tag:0ZGOQr9mN7kmPKEf810/8w==,type:str]
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT2lneU1uUzhNNUp2SVRw
            emNtREd2R0ZRTmV3WWc2U21kNmxiYXhsK0hVCjZoWk51TGJhK1ZMcUpkTUY2OGN1
            Qk01UUdEQ1VmTTIrTDVDaDd0S2pjL28KLS0tIFVxSFdBK1ZUY0pCOXpjZGtQQ1lK
            RFBUaXpTS1VMdjYxd0JDbmpxVzhxL28K74kp415kLCAtI41H3fvVyX/6TAmz1ipG
            h8Hm8vqvMafY6xsc0lfgXPcpHgkHHx9kBV7c8mJ4QJRXYzWd8tQHcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7rq0snpc5k39qw68mw0z48ndjgr0a4pdu6ehmcfn4zk8utc7dxqxaxn6g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T11:20:39Z"
    mac: ENC[AES256_GCM,data:84m16axQxJz/TmJQtDzScweyin6SPsMyExR9GxytqQgxj4ZYkjtKJey1sEyhNAhGjmsQJUp/sue6ReXKsrGLDA+nGfJZ7PL58He43W7vw088rGaxAiKT4UMVuiHmCATPf8+AcR5GaZ3MtbdI38ULt9LuruD0iIqovBVqlZXn2UQ=,iv:hOo/F2vnwvDbRMd2A9aNRSP21AANPonzvlxvNpYaEto=,tag:Aclb83WB02YKXr5EzlJT1w==,type:str]
    version: 3.13.1
