apiVersion: v1
data:
    admin_access_key_id: ENC[AES256_GCM,data:It/GJRivWlw9dpz4+5IjaKThg+s=,iv:PSJoHOTFb4zSfUheHQonEyBxAPSvUO4DgWMnOgPtpEY=,tag:BH5jU79GfXwp0yzvvIv8Pw==,type:str]
    admin_secret_access_key: ENC[AES256_GCM,data:hQDGtUr7blKCJamjhY4WPyAhC0IGruDPdYxaDWD7ekzkDpeJ,iv:jAGguX627stHPiLBwyu8sBO65kp1I8buaLP5MsTiOnU=,tag:ucwTZEpZdrA0hNSHeAU2uw==,type:str]
    read_access_key_id: ENC[AES256_GCM,data:Z8+BPX/J9nsA0asivEzTSkjobrE=,iv:+LBpY3sPkjbLxnd2JPnXU2E8fZoi3qDZLEkQ7XW/wuQ=,tag:fegkpKQGCQzSMb4NAZIgKA==,type:str]
    read_secret_access_key: ENC[AES256_GCM,data:xBG/vyMusaEB5MG43O2fdldzX9RmIU4wzIAar4/yT95ZwcHz,iv:BYNUcNQi+CptFEHa6ntuBtkMfWlTpi9KOoQ3RmyBais=,tag:Ut/jWs9WpG9b9xCppezsFw==,type:str]
    seaweedfs_s3_config: ENC[AES256_GCM,data:EF0y9S3wfZkJ/yjBn0SO15h9K7GQBzTaQarQKqKZ+nqMoE0l0IWX72NAmcek6zcOIkKLSPvLWb+/KdhyMDWXaa2vjFEDd3D5CITvJnNFX2FrX4wD89H+ExzOccrgUfjr+Uur25WckJusplRhoP9w61X09GJTjsbXtuk+ZGiJAuYYrS8q6Y3n6Ju3zwsQdzAo2iOhnv60XXBiwwEh6rnXSNocFWN/fLPMl5a7u6ylCLD0GyPH4zjk9ptzOB7KkWHcEd6emtfEHG/IBu9u8kGdp3O9EsOZIFa03KamQ+TWMLUSGzlA9j2U6U6myC13d8emUbZHHrh8r0snacJzoFQilvZy3fm1Y4fu6AGk4X13Ml3QW4r1koZajt4o7b6P9EFREOenJpcl25lfoHWFUJQDZYtRacn/960cLx9qrwFqgHG/YgOOXkV90y2sd0jhBBPkvLfyrqPkKc/C2Rda3OamOyC9TasY99v246it3wURv4rbZZIT1Bg9VnsO93cghEY6,iv:wwBuZCgyLoRgIzqn0uowbmHD1gFTpu6NCt/QF0U+m4s=,tag:vEARTtS8xGPbCYax4VZKKA==,type:str]
kind: Secret
metadata:
    name: seaweedfs-s3-secret
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR1FYVU85NzM0MHVuTTM4
            OTBxbjZBUVJTQVM4Qzgxc3pma1dwNjBRbjBzCjlIWnZrZUNRcTk0VkxHYTlaTmgr
            dDEwbXVudFd3dHVhUyswMnZoUDU0c2MKLS0tIHJKRjVCSm1KTEhQOVZFb3JQem5Z
            NHNPNHdaNjlqUTJBM2pPRUxOM1N2ZFEK74iJUtDytDuRk0uqATywZAowXgO+051e
            3+gwYMqAloCKb9SgWIckUh86chnCnD3csljZMOngbw0XlVPsrCc3TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7rq0snpc5k39qw68mw0z48ndjgr0a4pdu6ehmcfn4zk8utc7dxqxaxn6g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T10:43:48Z"
    mac: ENC[AES256_GCM,data:2duBla3fClHTBluQU2qDhYoQnVhJ+unk7ugsDkpMlblrx3Hk2dud6SDl8ABHmpGJzCR0KVwZhyP+5hvnq+IrYXQ6naKErp7pVwvUCQWPQLYleQQvfSS2Hb60v+UDfz/3PFKTexHV3lFzM3stLIHNRUUwBpzdGb3z8lQRxOJ4vr4=,iv:eP5hpWy1UbzKGySY20dG2ot1i5mKogVaTorrnvx230w=,tag:Qa6ktlph5SvOGuD4OUxOUw==,type:str]
    version: 3.13.1
