apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  url: oci://quay.io/cilium/charts/cilium
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "${cilium_version}"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: kube-system
  # ref: https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
  values:
    cluster:
      name: default
    # points to control plane
    k8sServiceHost: dean-homelab
    k8sServicePort: 6443
    # bypasses iptables, use eBPF instead
    kubeProxyReplacement: true
    bpf:
      # Source NAT for traffic going out of the cluster
      # uses node ip for traffic
      # could be disabled when BGP is enabled
      masquerade: true
    # required for routing between different locations
    routingMode: tunnel
    tunnelProtocol: vxlan
    l2announcements:
      enabled: true
    encryption:
      enabled: true
      type: wireguard
      nodeEncryption: true
    # IP Address Management
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16
        clusterPoolIPv4MaskSize: 24
    gatewayAPI:
      enabled: true
    hostFirewall:
      enabled: true
    operator:
      replicas: 1
    # Network Observability
    hubble:
      relay:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 512Mi
