apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/nextcloud-postgresql.yaml
  - secrets/nextcloud-redis.yaml
  - nextcloud-route.yaml
  - ../base/nextcloud
patches:
  - path: nextcloud-versions.yaml
