apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cilium-ip-pool
  namespace: gateway-system
spec:
  blocks:
    - cidr: "10.101.2.8/32"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-l2-policy
  namespace: gateway-system
spec:
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - dean-homelab
  loadBalancerIPs: true
  interfaces:
    - ^br0$
