apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 24h
  url: oci://ghcr.io/grafana-community/helm-charts/loki
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "${loki_version}"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  dependsOn:
    - name: prometheus-stack
  interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: loki
    namespace: monitoring
  # ref: https://github.com/grafana-community/helm-charts/blob/main/charts/loki/values.yaml
  # root: https://github.com/fluxcd/flux2-monitoring-example/blob/main/monitoring/controllers/loki-stack/release.yaml
  values:
    defaults:
      extraEnv:
        # ref: https://grafana.com/docs/loki/latest/configure/examples/thanos-storage-configs/#s3-example
        # these are the default AWS SDK env variables
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: seaweedfs-s3-secret
              key: admin_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: seaweedfs-s3-secret
              key: admin_secret_access_key
    loki:
      commonConfig:
        replication_factor: 1
      # single tenant: allow cluster wide access
      auth_enabled: false
      serviceMonitor:
        enabled: true
        labels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      storage:
        # better s3 client for Seaweedfs
        use_thanos_objstore: true
        bucketNames:
          chunks: chunks
          ruler: ruler
        object_store:
          type: s3
          s3:
            endpoint: "seaweedfs-s3:8333"
            insecure: true
      # ref: https://grafana.com/docs/loki/latest/operations/storage/schema/
      schemaConfig:
        configs:
          - from: "2026-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
    # faster deployments and less resource usage
    test:
      enabled: false
    lokiCanary:
      enabled: false
    # disable cache for slower queries but less resource usage
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    deploymentMode: Monolithic
    singleBinary:
      replicas: 1
      # used for accumulation before push to s3
      # if deleted possibly all logs are pushed
      persistence:
        storageClass: "local-path"
        size: 10Gi
    # only used if loki.deploymentMode=SimpleScalable
    # ref: https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/
    backend:
      replicas: 0
    write:
      replicas: 0
    read:
      replicas: 0
    # make discoverable metrics collect
    extraObjects:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: loki-datasource
          labels:
            app: loki
            chart: loki
            release: loki
            grafana_datasource: "1"
            app.kubernetes.io/part-of: kube-prometheus-stack
        data:
          # ref: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
          # ref: https://grafana.com/docs/grafana/latest/datasources/loki/configure-loki-data-source/
          loki-datasource.yaml: |-
            datasources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki:{{ .Values.loki.server.http_listen_port }}
              editable: false
