apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 24h
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "${prometheus_version}"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      # Automatically rollback on failure
      remediateLastFailure: true
  chartRef:
    kind: OCIRepository
    name: prometheus-stack
    namespace: monitoring
  # ref: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: false
    grafana:
      admin:
        existingSecret: grafana
        # username=admin
        userKey: username
        passwordKey: password
      persistence:
        enabled: true
        type: sts
        storageClassName: "longhorn-2node"
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        finalizers:
          - kubernetes.io/pvc-protection
    kubeProxy:
      enabled: false
    prometheus:
      prometheusSpec:
        # delete data older than 10 days or larger than 18Gi
        retention: 10d
        retentionSize: 18GiB
        resources:
          requests:
            cpu: 200m
            memory: 2.5Gi
          limits:
            memory: 2.5Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "longhorn-2node"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
