apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway-system
      sectionName: https-monitor
  hostnames:
    - "monitor.deanqx.com"
  rules:
    - filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Strict-Transport-Security
                value: "max-age=15552000"
      backendRefs:
        - name: prometheus-stack-grafana
          kind: Service
          port: 80
